grpc:
    server_addresses:
      - 0.0.0.0
    server_port: 51703
    num_threads: 10
    static_external_macs: []
p4:
    enabled: true
    driver: "tdi"
    representors:
      port_mux: "port-mux"
      vrf_mux: "vrf-mux"
      grpc_acc: "host"
      grpc_host: "00:20:00:00:14:48"
      phy0_rep: "port0"
      phy1_rep: "port1"
    config:
        p4info_file: .../p4files/linux_network.p4info.txt
        bin_file: ../p4files/linux_network.pb.bin
        conf_file: ../p4files/linux_network.conf
        sde_path: /root/acc_sdk_4445/p4sde/install
linux_frr:
    enabled: true
    default_vtep: "vxlan-vtep"
    port_mux: "eth5"
    vrf_mux: "eth4"
netlink:
    enabled: true
    poll_interval: 1
    phy_ports:
      - name: "eth1"
        vsi: 0
      - name: "eth3"
        vsi: 1
loglevel:
    db: INFO
    grpc: INFO
    linux_frr: INFO
    netlink: INFO
    p4: DEBUG
